ROASTS = {
    "openings": [
        "sach bolu?",
        "real talk—",
        "ek baat clear hai—",
        "seedhi baat bolta hu—",
        "honestly—",
        "sun bhai—",
        "seedha bol raha hu—",
    ],
    "default": [
        "effort dikh raha hai, direction missing hai.",
        "confidence full hai, par base weak hai.",
        "scene simple tha, tu ne khud complicated bana diya.",
        "try karta hai, par output match nahi karta.",
        "logic beech mein hi drop ho jaata hai.",
        "presence hai, impact doubtful lag raha hai.",
        "system chal raha hai, par processing faulty hai.",
        "energy galat jagah waste kar raha hai.",
        "kaam kam, hawa zyada hai.",
        "itna bhi off kaise ho sakta hai banda?",
    ],
    "repetitive": [
        "same cheez repeat kar raha hai, thoda upgrade kar.",
        "ek hi loop me atka hua lag raha hai.",
        "content change nahi ho raha, bas repeat ho raha hai.",
        "itna repeat kar raha hai ki lag raha hai system hang ho gaya.",
        "bhai tu broken record ban gaya hai kya?",
    ],
    "npc": [
        "reaction zyada, original thought kam.",
        "template jaisa lagta hai sab kuch.",
        "koi uniqueness dikh nahi rahi honestly.",
        "npc energy aa rahi hai full.",
        "tu khud sochta bhi hai ya copy paste hi karta hai?",
    ],
    "overthink": [
        "itna likhne ke baad bhi point clear nahi hai.",
        "zyada bol raha hai, keh kuch nahi raha.",
        "words zyada, meaning kam.",
        "essay likh diya, par conclusion missing hai.",
        "dimag chal raha hai par direction galat hai.",
    ],
    "dry": [
        "itna silent rehta hai ki presence doubtful lagti hai.",
        "conversation me hai ya background process, samajh nahi aata.",
        "itna chup rehta hai ki lagta hai system offline hai.",
        "presence zero, existence questionable.",
    ],
    "kill_low": [
        "bas wahi issue hai.",
        "samajh aa raha hoga.",
        "thoda soch lega toh sudhar jayega.",
        "abhi bhi time hai fix karne ka.",
    ],
    "kill_mid": [
        "aur wahi sabko dikh raha hai.",
        "aur wahi repeat ho raha hai.",
        "aur wahi sab ignore nahi kar pa rahe.",
        "aur wahi problem baar baar aa rahi hai.",
    ],
    "kill_high": [
        "aur honestly change bhi nahi ho raha.",
        "aur ye expected hi tha.",
        "aur ab toh habit ban chuki hai.",
        "aur sach bolu toh koi surprise nahi hai.",
    ],
    "fatal": [
        "honestly… jo dikh raha hai wahi kaafi hai.",
        "itna explain karne ki zarurat nahi hai.",
        "koi bhi serious nahi le raha, bas samajh le.",
        "ye stage cross ho chuki hai, ab bas accept kar.",
        "scene khatam hai, bas tu hi nahi samajh raha.",
    ]
}
